//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comp2007TeamProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class csgo
    {
        public int gameID { get; set; }
        public string team1 { get; set; }
        public string team2 { get; set; }
        public int roundsWon { get; set; }
        public int spectators { get; set; }
        public int totalPoints { get; set; }
        public string mapPlayed { get; set; }
        public string winner { get; set; }
        public int roundsWonTeam2 { get; set; }
        public int totalPointsTeam2 { get; set; }
    }
}
