//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comp2007TeamProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dota
    {
        public int gameID { get; set; }
        public string team1 { get; set; }
        public string team2 { get; set; }
        public int killsTeam1 { get; set; }
        public int killsTeam2 { get; set; }
        public int objectivesTeam1 { get; set; }
        public int objectivesTeam2 { get; set; }
        public string winner { get; set; }
        public int spectators { get; set; }
        public int weekOfGame { get; set; }
    }
}
